name: test logstash patterns
on: [push, pull_request]

jobs:
  test_patterns:
      runs-on: ubuntu-latest
      steps:
      - name: add logstash repo
        uses: myci-actions/add-deb-repo@4
        with:
            repo: deb https://artifacts.elastic.co/packages/8.x/apt stable main
            repo-name: elastic-8.x
            keys: D27D666CD88E42B4
      - name: install logstash
        run: sudo apt-get install logstash
      - name: add logstash to path
        run: echo "/usr/share/logstash/bin" >> $GITHUB_PATH
      - name: fix directory permissions of logstash data directory
        run: sudo chmod 777 /usr/share/logstash/data
      - name: Checkout code
        uses: actions/checkout@v3
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.9'
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install tox tox-gh-actions
      - name: run tests
        run: tox -v -c tox.ini
